require('core.plug')
require('core.options')
require('core.keymap')
require('core.filetype')

require('Plugin.coc')
require('Plugin.lualine')
require('Plugin.Imchange')
require('Plugin.treesitter')
require('Plugin.hlchunk')
